name: Release

on:
  push:
    tags:
    - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1
      with:
        channel: 'stable'
    - run: flutter pub get
    - run: flutter test
    - run: cd example && flutter build apk --debug --split-per-abi
    - uses: montudor/action-zip@v0.1.0
      with:
        args: zip -qq -r ./apks.zip . -i ./build/app/outputs/apk/debug
    - uses: svenstaro/upload-release-action@1.0.1
      with:
        repo_token: ${{ secrets.token }}
        file: ./apks.zip
        asset_name: example_app.zip
        tag: ${{ github.ref }}
        overwrite: true
